/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juegos.ruletaPremios;

import casino.JFrame_Principal;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Meybe
 */
public class ruletaVentana extends javax.swing.JFrame {
    Double saldo;
    List<String> premios;

    /**
     * Creates new form ruletaVentana
     * @param saldo
     * @param premios
     */
    public ruletaVentana(Double saldo, List<String> premios) {
        initComponents();
        this.saldo = saldo;
        this. premios = new ArrayList<>(); 
    }
    
    public void setSaldo(Double saldo){
        this.saldo = saldo;
    }
    
    public void setPremios(List<String> premios){
        this.premios = premios;
    }
    
    public void actualizarSaldo(){
        JFrame_Principal.principalWindow.setSaldo(saldo);
    }
    
    public void actualizarPremios(){
        JFrame_Principal.principalWindow.setPremios(premios);
    }


    /**
     * Creates new form ruletaVentana
     */
    public ruletaVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
